module(name = "pydhcplib3")

VER_PYTHON = "3.11"

bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "buildifier_prebuilt", version = "8.2.0.2", dev_dependency = True)
bazel_dep(name = "zstd", version = "1.5.7.bcr.2")

# DRY release version
release_metadata = use_repo_rule(
    "//:bazel/release_metadata.bzl",
    "release_metadata",
)

release_metadata(
    name = "release_metadata",
    manifest = "//:.github/release-please-manifest.json",
    project_name = "pydhcplib3",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = VER_PYTHON,
    requirements_lock = "//:requirements_lock.txt",
)
use_repo(pip, "pypi")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    ignore_root_user_error = True,
    is_default = True,
    python_version = VER_PYTHON,
)

USE_PYTHON="python_{}".format(VER_PYTHON.replace(".", "_"))
use_repo(python, USE_PYTHON)
